version: '3'
services:
  db:
    image: mariadb:10.6
    volumes:
      - ./db_data:/var/lib/mysql
    expose:
      - 3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ksD8k3hjj
    networks:
      - comicDevs
    container_name: comic_db
  
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on: 
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=ksD8k3hjj
    ports:
      - 8080:80
    volumes:
      - ./phpmyadmin_data:/sessions
    networks:
      - comicDevs
    container_name: comic_phpmyadmin
  
  app:
    build:
      context: "./"
      dockerfile: "Dockerfile"
    volumes:
      - ./apps_data:/home/dev_user
    ports:
      - 12345:8888
    networks:
      - comicDevs
    privileged: true
    depends_on:
      - db
    container_name: comic_app

networks:
  comicDevs:
    driver: bridge