FROM jenkins/jenkins:2.333-jdk11

USER root
RUN apt-get update && apt-get install -y lsb-release

USER jenkins

RUN mkdir /var/jenkins_home/.ssh && \
    cd /var/jenkins_home/.ssh && \
    ssh-keygen -t rsa -N "" -f /var/jenkins_home/.ssh/id_rsa && \
    chmod 700 /var/jenkins_home/.ssh

ADD ./copy_sshkey.sh /tmp/copy_sshkey.sh